In [16]:
#1. Create a null vector of size 10 but the fifth value which is 1.

import numpy as np

n = np.zeros(10)
n[4]=1
n


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [18]:
#2. Create a vector with values ranging from 10 to 49.

m =  np.arange(10,50)
m

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [41]:
#3. Create a 3x3 matrix with values ranging from 0 to 8

z = np.arange(0,9)
m = z.reshape(3,3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [54]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0]

l = np.array([1,2,0,0,4,0])
z = np.where(l>0)
print("Indices of non-zero elements are ",z)

Indices of non-zero elements are  (array([0, 1, 4], dtype=int64),)


In [59]:
l = np.array([1,2,0,0,4,0])
print("Indices of non-zero elements are : ")
for i in range(len(l)):
    if l[i] !=0:
        print(i,end = " ")

Indices of non-zero elements are : 
0 1 4 

In [68]:
#5. Create a 10x10 array with random values and find the minimum and maximum values.

o = np.random.randint(0,50,(10,10))
print(o)
p = np.max(o)  #o.max()
print("The maximum value is :",p)
q = np.min(o)   #o.min()
print("The maximum value is :",q)

[[18 30 32 41 29 13 22 33 19 36]
 [13  2 39 44 47 16 20 10 17 40]
 [31  7 26 48 48 47 36  8 48 33]
 [48 24  4 31  6 33 46 27  8 36]
 [47 14 16 28  6  0 37 44 47 30]
 [45  5 12 29 25 30  0  7 38  4]
 [17  6 22 29 16 21 30 20 36 17]
 [23 11  6 47 25 37 27 49 25 31]
 [40 30 27 41 34  5 13 11 31  0]
 [11 19  7 32 46 15 44 26 17 46]]
The maximum value is : 49
The maximum value is : 0


In [75]:
# 6. Create a random vector of size 30 and find the mean value.

t = np.random.rand(30)
y = t.mean()
y

0.4888370548296305

In [74]:
y = np.random.randint(2,90,30)
z=y.mean()
z

44.666666666666664